### ISSUE TITLE
No peer were received from any trackers

### ISSUE THREAD

**Issue by robertt202** [kzahel/jstorrent-legacy-app#61]
I am trying to download torrents from EZTV.IT, rarbg, ettv, and G2G and keep getting the above message.
I am getting some downloads from other sources.

thanks
p.s. I previously reported the eztv.it and I think you said they didn't support 64 bit something or other ?
thanks for your help

**Comment by kzahel** [comment]
Hi. When is the last time you updated (I assume you are running from source?)
I think I fixed this issue a few weeks ago and released 2.3.0 in the app store. It was a base32 encoding problem... base32 is ridiculous, base16 magnet links are much simpler :-)

**Comment by robertt202** [comment]
I downloaded it from the playstore - is there an update from that one?
I'm running it on a chromebook

can you give me instructions for updating it?

-----Original Message-----

**Comment by kzahel** [comment]
It will automatically update if you have it installed from the google chrome web store. So you should already have the latest version.

But the problem could also be your ISP blocking traffic to trackers. But perhaps they don't block DHT, which I will be adding soon

**Comment by robertt202** [comment]
That's what's baffling me. I can use it on the chromebook sometimes. and I can use bittorreent on my desktop without getting the errors.

weird, huh?

-----Original Message-----

**Comment by kzahel** [comment]
Not too weird, since uTorrent can get peers through the DHT and JSTorrent can't yet, this could be the reason why sometimes JSTorrent is not getting any peers.

Do you try clicking on the option to add public trackers? Does that help?

In the "trackers" tab, what kind of errors do you see? timeouts?

**Comment by rsalmond** [comment]
I dunno if this is related but I've seen this effect with torrents which contain multiple trackers. JSTorrent only seems to be adding the first one to the trackers tab. Adding some trackers back in sorts it out for me.

**Comment by kzahel** [comment]
@rsalmond that sounds like a very bad bug! any chance you can mail me the .torrent file in question to graehlarts@gmail.com so I can fix it?

**Comment by rsalmond** [comment]
@kzahel sent!

**Comment by kzahel** [comment]
@rsalmond Thanks! It was a very simple problem. I was being too strict to the specification. There's not supposed to be both "announce" and "announce-list" in the torrent file, but since adding more trackers never hurt, I'll just add them both

https://github.com/kzahel/jstorrent/commit/75804004be1be438a965d413f0210e117f93aa07

Thanks again! I owe you!!!

**Comment by rsalmond** [comment]
Sweet, glad to hear it! Happy to help, love this app.

**Comment by kzahel** [comment]
I think I'll probably put out an update tomorrow too, this seems like a very good fix that could help a lot of users.

**Comment by robertt202** [comment]
thanks for keeping me in the loop.

-----Original Message-----

**Comment by dannybez** [comment]
@kzahel I am a big fan of jstorrent on my chromebook. Great app. Recently getting this error message every time I try to download - ' No peers were received from any trackers. Unable to download etc'. I click add public trackers - same message. I try different sites/popular torrents - same message. I am running version 2.3.9. Any thoughts or assistance? Thanks in advance for help.

**Comment by kzahel** [comment]
Can you try using a torrent file instead of magnet link? There seems to be
an issue with them at the moment that I'm looking into

**Comment by dannybez** [comment]
Thanks for coming back to me - most appreciated. I usually use the
extension. Tried a manual add of torrent file and still same error. I know
the torrent is working as I tried it on my partners computer. Always last
error on trackers is 'timeout'. Thanks for looking into this.

**Comment by kzahel** [comment]
Hey, I think I figured out the problem. I pushed an update to version 2.3.10. Can you test and see if it's working for you again?

**Comment by robertt202** [comment]
still using 2.3.9 and it's working fine for me.

-----Original Message-----

**Comment by Desorma** [comment]
I've been having the same problems recently, the 2.3.10 update fixed it for me. Thanks a bunch!

**Comment by dannybez** [comment]
2.3.10 fixed it for extension and manual upload. Thanks so much, most
appreciated.

**Comment by sirafali** [comment]
Still have the same problem as those above. Using a Acer Chromebook. Some times i get peers instantly and all torrents begins to download immediately. Next day, no torrents what so ever will recieve peers. Only getting the "Unable to download etc" -error message. I've tried to download torrents from different torrent sites and torrents with 500+ seeders. Its incredibly annoying that it's only works every once in a while. Also, ifi try to download a torrent and it wont start, it seems that that particular torrent wont begin download ever.  Plenty of space on my SSD aswell. Any ideas what might cause this?

**Comment by kzahel** [comment]
The first thing to try is to use a .torrent file instead of a magnet link,
or vice versa. Try using a magnet link if you're trying .torrent files.
They typically have a different set of trackers, which will give it a
better chance of working.

I know this is a pretty big problem, and I need to get to work on
trackerless support

**Comment by sirafali** [comment]
Wow thanks for the quick response kzahel! 
I think i just discovered what the problem was, but i'm not 100 % sure. There seems to be a problem when downloading torrents uploaded by the user EZTV. No matter what torrent site you use.

**Comment by odococo** [comment]
I've the same problem. Yesterday everything was working fine. Today it's impossible to download anything. I tried differente torrent, .torrent file and magnet link, but i keep receiving that message.
